# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build  Gradle
      run: ./gradlew build
    - name: Pruebas unitarias
      run: ./gradlew test
    - name: Analisis Sonar
      run: ./gradlew build jacocoTestReport sonarqube --info
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Sonar Build Breaker
      uses: DevOps575/sonar-build-breaker@v1.0.0
      with:
        project_key: londono652_apisaludo
        sonar_token: ${{ secrets.SONAR_TOKEN }}
        sonar_url: https://sonarcloud.io
        sonar_branch: main
    ####otro
